config/routes.rb
Rails.application.routes.draw do
  resources :accounts
  get    '/signup', to: 'accounts#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  root    'static_pages#home'
  get 'search' => 'static_pages#search'
  get 'news' => 'static_pages#news'
  get 'store' => 'static_pages#store'
end

app/models/account.rb
class Account < ActiveRecord::Base
  attr_accessor :remember_token
  has_many :players
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  before_save { email.downcase!}
  validates :name,  presence: true, length: { maximum: 10, minimum: 5 }
  validates :email, presence: true,  length: { maximum: 30 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: false
  has_secure_password

  def Account.sha1_encrypt(string)
    Digest::SHA1.hexdigest string
  end

  def Account.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def Account.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = Account.new_token
    update_attribute(:remember_digest, Account.digest(remember_token))
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
end

app/models/ban.rb
class Ban < ActiveRecord::Base
end

app/models/guild.rb
class Guild < ActiveRecord::Base
end

app/models/guild_invite.rb
class GuildInvite < ActiveRecord::Base
end

app/models/guild_rank.rb
class GuildRank < ActiveRecord::Base
end

app/models/house.rb
class House < ActiveRecord::Base
end

app/models/house_datum.rb
class HouseDatum < ActiveRecord::Base
  self.table_name = 'house_data'
end

app/models/house_list.rb
class HouseList < ActiveRecord::Base
end

app/models/killer.rb
class Killer < ActiveRecord::Base
end

app/models/player.rb
class Player < ActiveRecord::Base
end

app/models/player_death.rb
class PlayerDeath < ActiveRecord::Base
end

app/models/player_item.rb
class PlayerItem < ActiveRecord::Base
end

app/models/player_killer.rb
class PlayerKiller < ActiveRecord::Base
end

app/models/player_skill.rb
class PlayerSkill < ActiveRecord::Base
end

app/models/player_spell.rb
class PlayerSpell < ActiveRecord::Base
end

app/models/server_config.rb
class ServerConfig < ActiveRecord::Base
  self.table_name = 'server_config'
end

app/models/server_motd.rb
class ServerMotd < ActiveRecord::Base
  self.table_name = 'server_motd'
end

app/models/tile.rb
class Tile < ActiveRecord::Base
end

app/models/tile_item.rb
class TileItem < ActiveRecord::Base
end

app/models/tile_store.rb
class TileStore < ActiveRecord::Base
  self.table_name = 'tile_store'
end

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top.navbar-inverse
  %div.container
    %nav
      = link_to "Helera", root_path, id: "logo"
      %ul.nav.navbar-nav.navbar-right
        %li
          = link_to "Home", root_path
        %li
          = link_to "News", news_path
        %li
          = link_to "Store", store_path
        %li
          = link_to "Search", search_path

        - if logged_in?
          %li
            = link_to "Players", '#'
          %li.dropdown
            %a.dropdown-toggle{ :href => "#", "role" => "button", "data-toggle" => "dropdown", "data-taget" => "#"}
              Account
              %b.caret
            %ul.dropdown-menu{"role" => "menu"}
              %li= link_to "Profile", current_account
              %li= link_to "Settings", "#"
              %li.divider
              %li= link_to "Log out", logout_path, method: "delete"
        - else
          %li
            = link_to "Log In", login_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tfs</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <% flash.each do |message_type, message|%>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>

app/views/shared/_error_messages.html.haml
= if @account.errors.any?
  #error_explanation
    .alert.alert-danger
      = "The form contains #{pluralize(@account.errors.count, "error")}"
    %ul
      = @account.errors.full_messages.each do |msg|
        %li= msg